// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBEyjiJOQxksq81cI865BN4T28i-P1gGGo",
    authDomain: "veteran-development.firebaseapp.com",
    projectId: "veteran-development",
    storageBucket: "veteran-development.appspot.com",
    messagingSenderId: "32851885972",
    appId: "1:32851885972:web:c4786e1703493d24ecd981",
    measurementId: "G-RZ2GYNWZ79",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8CbivBU82h3WhxgoZ0mkdMq5y1OEfbQk',
    appId: '1:32851885972:android:d920f90e0bb70673ecd981',
    messagingSenderId: '32851885972',
    projectId: 'veteran-development',
    storageBucket: 'veteran-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbrgwKWeMZ69SHecID9NFHohsA7v8YOss',
    appId: '1:32851885972:ios:1f70471fce23766fecd981',
    messagingSenderId: '32851885972',
    projectId: 'veteran-development',
    storageBucket: 'veteran-development.appspot.com',
    iosClientId:
        '32851885972-39m4c4lb48qj9p40542l7o0d8hebfoaa.apps.googleusercontent.com',
    iosBundleId: 'info.veteranam.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbrgwKWeMZ69SHecID9NFHohsA7v8YOss',
    appId: '1:32851885972:ios:658759515917d638ecd981',
    messagingSenderId: '32851885972',
    projectId: 'veteran-development',
    storageBucket: 'veteran-development.appspot.com',
    iosClientId:
        '32851885972-dug7bniacnr414ninjv0uc45v527q1j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
