// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAWXzOYOBDQXFlU6Gp_8BYyvk5_L9Ev3dU",
    authDomain: "veteran-production.firebaseapp.com",
    projectId: "veteran-production",
    storageBucket: "veteran-production.appspot.com",
    messagingSenderId: "326120302123",
    appId: "1:326120302123:web:2e7f57b9f1be4c39edac6e",
    measurementId: "G-5K1QYSG097",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMWzGq_-aa1c-ywngHWm-1gL_R9uBYsFg',
    appId: '1:326120302123:android:bc4862ae5990f5c0edac6e',
    messagingSenderId: '326120302123',
    projectId: 'veteran-production',
    storageBucket: 'veteran-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC23K7nwAkDvjcZAs5auqB1SjChELepAQ4',
    appId: '1:326120302123:ios:f7fe329bb88f4091edac6e',
    messagingSenderId: '326120302123',
    projectId: 'veteran-production',
    storageBucket: 'veteran-production.appspot.com',
    iosClientId:
        '326120302123-6imcoq7lddeov8i8dcicp15cjn6a418u.apps.googleusercontent.com',
    iosBundleId: 'info.veteranam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC23K7nwAkDvjcZAs5auqB1SjChELepAQ4',
    appId: '1:326120302123:ios:f7fe329bb88f4091edac6e',
    messagingSenderId: '326120302123',
    projectId: 'veteran-production',
    storageBucket: 'veteran-production.appspot.com',
    iosClientId:
        '326120302123-6imcoq7lddeov8i8dcicp15cjn6a418u.apps.googleusercontent.com',
    iosBundleId: 'info.veteranam',
  );
}
